In [1]:
import pandas as pd
import numpy as np

In [2]:
raw_df = pd.read_csv('bullying_2018.csv')

In [3]:
raw_df['all values'] = raw_df
raw_df['list of values'] = raw_df['all values'].apply(lambda x: x.split(';'))
raw_df['len'] = raw_df['list of values'].apply(len)
len(raw_df['all values'])

56981

In [4]:
columns_list = list(raw_df.columns[0].split(';'))
raw_df.drop(raw_df.columns[0], axis=1, inplace=True)

In [5]:
df = pd.DataFrame(index=range(56981), columns=columns_list)

In [6]:
for column in columns_list:
    col_index = columns_list.index(column)
    
    for i in range(0, 56981):
        df.iloc[i, col_index] = raw_df.iloc[i, 1][col_index]

In [7]:
df.replace(' ', np.nan, inplace=True)

In [8]:
df.dropna(inplace=True)

In [11]:
df.to_csv('bullying_clean1.csv', index=False)

In [12]:
df

,record,Bullied_on_school_property_in_past_12_months,Bullied_not_on_school_property_in_past_12_months,Cyber_bullied_in_past_12_months,Custom_Age,Sex,Physically_attacked,Physical_fighting,Felt_lonely,Close_friends,Miss_school_no_permission,Other_students_kind_and_helpful,Parents_understand_problems,Most_of_the_time_or_always_felt_lonely,Missed_classes_or_school_without_permission,Were_underweight,Were_overweight,Were_obese
2,3,No,No,No,14 years old,Male,0 times,0 times,Never,3 or more,0 days,Sometimes,Always,No,No,No,No,No
5,6,No,No,No,13 years old,Male,0 times,1 time,Never,3 or more,0 days,Most of the time,Always,No,No,No,No,No
10,11,No,No,No,15 years old,Male,0 times,1 time,Never,3 or more,3 to 5 days,Most of the time,Always,No,Yes,No,No,No
22,23,No,No,Yes,13 years old,Male,0 times,2 or 3 times,Most of the time,3 or more,0 days,Rarely,Always,Yes,No,No,No,No
23,24,No,No,No,14 years old,Male,0 times,2 or 3 times,Most of the time,2,0 days,Always,Sometimes,Yes,No,No,Yes,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56972,57087,No,Yes,No,16 years old,Male,0 times,0 times,Rarely,3 or more,3 to 5 days,Rarely,Most of the time,No,Yes,No,No,No
56974,57089,No,No,No,16 years old,Male,0 times,2 or 3 times,Never,3 or more,0 days,Sometimes,Always,No,No,No,No,No
56975,57090,No,No,Yes,15 years old,Male,12 or more times,2 or 3 times,Rarely,3 or more,0 days,Most of the time,Sometimes,No,No,No,No,No
56976,57091,No,Yes,No,16 years old,Male,0 times,4 or 5 times,Sometimes,3 or more,0 days,Sometimes,Sometimes,No,No,No,Yes,No
56980,57095,No,Yes,Yes,16 years old,Female,0 times,0 times,Always,2,1 or 2 days,Rarely,Never,Yes,Yes,No,No,No